name: Logyee
main: top.zhrhello.logyee.bukkit.Logyee
author: zhrhello
version: ${version}
softdepend: [Multiverse-Core, Citizens, Essentials, EssentialsSpawn, ProtocolLib]
api-version: 1.13
commands:
  login:
    description: 使用密码登录
    usage: /<command> 密码
    aliases: [l]
  register:
    description: 注册密码
    usage: /<command> 密码 重复密码
    aliases: [reg]
  bindemail:
    description: 绑定邮箱,重置密码
    usage:
      |
      /<command> set 邮箱
      /<command> verify 验证码
    aliases: [bdmail]
  resetpassword:
    description: 忘记密码,重置密码
    usage:
      |
      /<command> forget
      /<command> re 验证码 新密码
    aliases: [repw]
  changepassword:
    description: 修改密码
    usage: /<command> 旧密码 新密码 重复新密码
    aliases: [changepw]
  logyee:
    description: 管理员管理指令
    usage:
      |
      §d§lLogyee 管理指令 (主命令可缩写 /ly):
      §a/<command> set/see cmdwhitelist|cw add|rm [指令] §9登录前允许执行的指令(支持正则)
      §a/<command> set/see ipreg|ir [数量] §9相同ip注册限制(默认2)
      §a/<command> set/see ipjoin|ij [数量] §9相同ip登录限制(默认2)
      §a/<command> set/see name|nm least|long [值] §9游戏名最小/最大长度(默认2/15)
      §a/<command> set/see reconnect|re [间隔] §9离开服务器重进间隔tick(默认60)
      §a/<command> set/see autokick|ak [秒数] §9自动踢出未登录(默认120,<1关闭)
      §a/<command> set/see/tp Spawn §9登录地点(默认world出生点)
      §a/<command> set/see chineseid|cnid on/off §9限制中文游戏名(默认开)
      §a/<command> set/see nodamage|nd on/off §9登录前免伤(默认开)
      §a/<command> set/see alb|afterloginback on/off §9登录后回退出点(默认开)
      §a/<command> set/see forceloginlocation|fsl on/off §9登录前强制在登录点(默认开)
      §a/<command> set/see deathrecord|dr on/off §9死亡退出记录位置(默认开)
      §e/<command> rmplayer|rmp [玩家名] §9管理员强制删除账户
      §e/<command> setpwd|sp [玩家名] [密码] §9管理员强制设置密码
      §3/<command> reload|re §9重载配置文件
    aliases: [ly, logy]
    permission: logyee.command.logyee